// <auto-generated />
using GolfStore.DataAccess.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GolfStore_L00181486.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260130133412_intial")]
    partial class intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GolfStore.Models.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            Abbreviation = "CAL",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/8/89/Callaway_Golf_Company_logo.svg",
                            Name = "Callaway"
                        },
                        new
                        {
                            BrandId = 2,
                            Abbreviation = "TAY",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/en/1/1f/Taylormade_logo.png",
                            Name = "TaylorMade"
                        },
                        new
                        {
                            BrandId = 3,
                            Abbreviation = "TIT",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/d/d6/Titleist_golf_logo.png",
                            Name = "Titleist"
                        },
                        new
                        {
                            BrandId = 4,
                            Abbreviation = "PIN",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/3/37/Ping-logo.png",
                            Name = "Ping"
                        },
                        new
                        {
                            BrandId = 5,
                            Abbreviation = "COB",
                            LogoUrl = "https://www.cobragolf.com/cdn/shop/files/COBRA-logo-2022-black-shopify-checkout_1724x.png?v=1689363641",
                            Name = "Cobra"
                        },
                        new
                        {
                            BrandId = 6,
                            Abbreviation = "MIZ",
                            LogoUrl = "https://upload.wikimedia.org/wikipedia/commons/3/34/Mizuno_logo.jpg",
                            Name = "Mizuno"
                        });
                });

            modelBuilder.Entity("GolfStore.Models.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Forgiveness")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("ClubId");

                    b.HasIndex("BrandId");

                    b.HasIndex("TypeId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("GolfStore.Models.Models.Clubtype", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("Clubtypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            ImgUrl = "/images/driver.png",
                            Type = "Driver"
                        },
                        new
                        {
                            TypeId = 2,
                            ImgUrl = "/images/fairwayWood.png",
                            Type = "Fairway Wood"
                        },
                        new
                        {
                            TypeId = 3,
                            ImgUrl = "/images/hybrid.png",
                            Type = "Hybrid"
                        },
                        new
                        {
                            TypeId = 4,
                            ImgUrl = "/images/iron.png",
                            Type = "Iron"
                        },
                        new
                        {
                            TypeId = 5,
                            ImgUrl = "/images/wedge.png",
                            Type = "Wedge"
                        },
                        new
                        {
                            TypeId = 6,
                            ImgUrl = "/images/putter.png",
                            Type = "Putter"
                        });
                });

            modelBuilder.Entity("GolfStore.Models.Models.Club", b =>
                {
                    b.HasOne("GolfStore.Models.Models.Brand", "Brand")
                        .WithMany("Clubs")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfStore.Models.Models.Clubtype", "Clubtype")
                        .WithMany("Clubs")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Clubtype");
                });

            modelBuilder.Entity("GolfStore.Models.Models.Brand", b =>
                {
                    b.Navigation("Clubs");
                });

            modelBuilder.Entity("GolfStore.Models.Models.Clubtype", b =>
                {
                    b.Navigation("Clubs");
                });
#pragma warning restore 612, 618
        }
    }
}
