// <auto-generated />
using System;
using GolfStore.DataAccess.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GolfStore.DataAccess.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260313211748_clubs")]
    partial class clubs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GolfStore.Models.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            Abbreviation = "CAL",
                            LogoUrl = "/images/brands/callaway-logo.png",
                            Name = "Callaway"
                        },
                        new
                        {
                            BrandId = 2,
                            Abbreviation = "TAY",
                            LogoUrl = "/images/brands/taylormade-logo.png",
                            Name = "TaylorMade"
                        },
                        new
                        {
                            BrandId = 3,
                            Abbreviation = "TIT",
                            LogoUrl = "/images/brands/titleist-logo.png",
                            Name = "Titleist"
                        },
                        new
                        {
                            BrandId = 4,
                            Abbreviation = "PIN",
                            LogoUrl = "/images/brands/ping-logo.png",
                            Name = "Ping"
                        },
                        new
                        {
                            BrandId = 5,
                            Abbreviation = "COB",
                            LogoUrl = "/images/brands/cobra-logo.png",
                            Name = "Cobra"
                        },
                        new
                        {
                            BrandId = 6,
                            Abbreviation = "MIZ",
                            LogoUrl = "/images/brands/mizuno-logo.png",
                            Name = "Mizuno"
                        });
                });

            modelBuilder.Entity("GolfStore.Models.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubId"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("Forgiveness")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("ClubId");

                    b.HasIndex("BrandId");

                    b.HasIndex("TypeId");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            ClubId = 1,
                            BrandId = 1,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/elyte.png",
                            Name = "Elyte",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 2,
                            BrandId = 1,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/elyte-x.png",
                            Name = "Elyte X",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 3,
                            BrandId = 1,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/elyte-triple-diamond.png",
                            Name = "Elyte Triple Diamond",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 4,
                            BrandId = 1,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/elyte.png",
                            Name = "Elyte",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 5,
                            BrandId = 2,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/Qi4D.png",
                            Name = "Qi4D",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 6,
                            BrandId = 2,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/Qi4D-Max.png",
                            Name = "Qi4D Max",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 7,
                            BrandId = 2,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/Qi4D-LS.png",
                            Name = "Qi4D LS",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 8,
                            BrandId = 3,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/GT1.png",
                            Name = "GT1",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 9,
                            BrandId = 3,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/GT4.png",
                            Name = "GT4",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 10,
                            BrandId = 3,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/GT3.png",
                            Name = "GT3",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 11,
                            BrandId = 4,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/G440-K.png",
                            Name = "G440 K",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 12,
                            BrandId = 4,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/G440-Max.png",
                            Name = "G440 Max",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 13,
                            BrandId = 4,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/G440-LST.png",
                            Name = "G440 LST",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 14,
                            BrandId = 5,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/OPTM-X.png",
                            Name = "OPTM X",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 15,
                            BrandId = 5,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/OPTM-Max-K.png",
                            Name = "OPTM Max-K",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 16,
                            BrandId = 5,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/OPTM-LS.png",
                            Name = "OPTM LS",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 17,
                            BrandId = 6,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/JPX-ONE.png",
                            Name = "JPX ONE",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 18,
                            BrandId = 6,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/JPX-ONE-Select.png",
                            Name = "JPX ONE Select",
                            Price = 500,
                            Stock = 12,
                            TypeId = 1
                        },
                        new
                        {
                            ClubId = 19,
                            BrandId = 1,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/X-Forged-Max.png",
                            Name = "X Forged Max",
                            Price = 1300,
                            Stock = 12,
                            TypeId = 4
                        },
                        new
                        {
                            ClubId = 20,
                            BrandId = 1,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/X-Forged.png",
                            Name = "X Forged",
                            Price = 1300,
                            Stock = 12,
                            TypeId = 4
                        },
                        new
                        {
                            ClubId = 21,
                            BrandId = 2,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/P790.png",
                            Name = "P790",
                            Price = 1300,
                            Stock = 12,
                            TypeId = 4
                        },
                        new
                        {
                            ClubId = 22,
                            BrandId = 2,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/P770.png",
                            Name = "P770",
                            Price = 1300,
                            Stock = 12,
                            TypeId = 4
                        },
                        new
                        {
                            ClubId = 23,
                            BrandId = 2,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/P7MB.png",
                            Name = "P7MB",
                            Price = 1300,
                            Stock = 12,
                            TypeId = 4
                        },
                        new
                        {
                            ClubId = 24,
                            BrandId = 3,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/T100.png",
                            Name = "T100",
                            Price = 1300,
                            Stock = 12,
                            TypeId = 4
                        },
                        new
                        {
                            ClubId = 25,
                            BrandId = 3,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/T250.png",
                            Name = "T250",
                            Price = 1300,
                            Stock = 12,
                            TypeId = 4
                        },
                        new
                        {
                            ClubId = 26,
                            BrandId = 4,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/G440-Irons.png",
                            Name = "G440",
                            Price = 1300,
                            Stock = 12,
                            TypeId = 4
                        },
                        new
                        {
                            ClubId = 27,
                            BrandId = 4,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/G440-HL-Irons.png",
                            Name = "G440 HL",
                            Price = 1300,
                            Stock = 12,
                            TypeId = 4
                        },
                        new
                        {
                            ClubId = 28,
                            BrandId = 5,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/King-Irons.png",
                            Name = "King",
                            Price = 1300,
                            Stock = 12,
                            TypeId = 4
                        },
                        new
                        {
                            ClubId = 29,
                            BrandId = 5,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/King-Tec-Irons.png",
                            Name = "King Tec",
                            Price = 1300,
                            Stock = 12,
                            TypeId = 4
                        },
                        new
                        {
                            ClubId = 30,
                            BrandId = 6,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/Pro-M13.png",
                            Name = "Pro M13",
                            Price = 1300,
                            Stock = 12,
                            TypeId = 4
                        },
                        new
                        {
                            ClubId = 31,
                            BrandId = 6,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/Pro-M15.png",
                            Name = "Pro M15",
                            Price = 1300,
                            Stock = 12,
                            TypeId = 4
                        },
                        new
                        {
                            ClubId = 32,
                            BrandId = 1,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/Elyte-Wood.png",
                            Name = "Elyte Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 33,
                            BrandId = 1,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/Elyte-X-Wood.png",
                            Name = "Elyte X Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 34,
                            BrandId = 1,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/Elyte-Triple-Diamond-Wood.png",
                            Name = "Elyte Triple Diamond Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 35,
                            BrandId = 2,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/Qi4D-Wood.png",
                            Name = "Qi4D Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 36,
                            BrandId = 2,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/Qi4D-Max-Wood.png",
                            Name = "Qi4D Max Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 37,
                            BrandId = 2,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/Qi4D-Tour-Wood.png",
                            Name = "Qi4D Tour Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 38,
                            BrandId = 3,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/GT1-Wood.png",
                            Name = "GT1 Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 39,
                            BrandId = 3,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/GT2-Wood.png",
                            Name = "GT2 Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 40,
                            BrandId = 3,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/GT3-Wood.png",
                            Name = "GT3 Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 41,
                            BrandId = 4,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/G440-SFT-Wood.png",
                            Name = "G440 SFT Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 42,
                            BrandId = 4,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/G440-Max-Wood.png",
                            Name = "G440 Max Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 43,
                            BrandId = 4,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/G440-LST-Wood.png",
                            Name = "G440 LST Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 44,
                            BrandId = 5,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/OPTM-X-Wood.png",
                            Name = "OPTM X Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 45,
                            BrandId = 5,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/OPTM-Max-Wood.png",
                            Name = "OPTM Max Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 46,
                            BrandId = 5,
                            Forgiveness = 0,
                            ImgUrl = "/images/clubs/OPTM-LS-Wood.png",
                            Name = "OPTM LS Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 47,
                            BrandId = 6,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/JPX-ONE-Wood.png",
                            Name = "JPX ONE Fairway",
                            Price = 300,
                            Stock = 12,
                            TypeId = 2
                        },
                        new
                        {
                            ClubId = 48,
                            BrandId = 1,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/Quantum-Max-Hybrid.png",
                            Name = "Quantum Max Hybrid",
                            Price = 300,
                            Stock = 12,
                            TypeId = 3
                        },
                        new
                        {
                            ClubId = 49,
                            BrandId = 2,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/Qi4D-Rescue.png",
                            Name = "Qi4D Rescue",
                            Price = 300,
                            Stock = 12,
                            TypeId = 3
                        },
                        new
                        {
                            ClubId = 50,
                            BrandId = 3,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/GT3-Hybrid.png",
                            Name = "GT3 Hybrid",
                            Price = 300,
                            Stock = 12,
                            TypeId = 3
                        },
                        new
                        {
                            ClubId = 51,
                            BrandId = 4,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/G440-Hybrid.png",
                            Name = "G440 Hybrid",
                            Price = 300,
                            Stock = 12,
                            TypeId = 3
                        },
                        new
                        {
                            ClubId = 52,
                            BrandId = 5,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/OPTM-Hybrid.png",
                            Name = "OPTM Hybrid",
                            Price = 300,
                            Stock = 12,
                            TypeId = 3
                        },
                        new
                        {
                            ClubId = 53,
                            BrandId = 6,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/JPX-ONE-Hybrid.png",
                            Name = "JPX ONE Hybrid",
                            Price = 300,
                            Stock = 12,
                            TypeId = 3
                        },
                        new
                        {
                            ClubId = 54,
                            BrandId = 1,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/Jaws.png",
                            Name = "Jaws",
                            Price = 200,
                            Stock = 12,
                            TypeId = 5
                        },
                        new
                        {
                            ClubId = 55,
                            BrandId = 2,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/MG5.png",
                            Name = "MG5",
                            Price = 200,
                            Stock = 12,
                            TypeId = 5
                        },
                        new
                        {
                            ClubId = 56,
                            BrandId = 3,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/Vokey-SM11.png",
                            Name = "Vokey SM11",
                            Price = 200,
                            Stock = 12,
                            TypeId = 5
                        },
                        new
                        {
                            ClubId = 57,
                            BrandId = 4,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/S259.png",
                            Name = "S259",
                            Price = 200,
                            Stock = 12,
                            TypeId = 5
                        },
                        new
                        {
                            ClubId = 58,
                            BrandId = 5,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/King-Wedge.png",
                            Name = "King Wedge",
                            Price = 200,
                            Stock = 12,
                            TypeId = 5
                        },
                        new
                        {
                            ClubId = 59,
                            BrandId = 6,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/Pro-T3.png",
                            Name = "Pro-T3",
                            Price = 200,
                            Stock = 12,
                            TypeId = 5
                        },
                        new
                        {
                            ClubId = 60,
                            BrandId = 1,
                            Forgiveness = 1,
                            ImgUrl = "/images/clubs/Odyssey.png",
                            Name = "Odyssey AI Dual",
                            Price = 200,
                            Stock = 12,
                            TypeId = 6
                        },
                        new
                        {
                            ClubId = 61,
                            BrandId = 1,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/Odyssey.png",
                            Name = "Odyssey AI Dual",
                            Price = 500,
                            Stock = 12,
                            TypeId = 6
                        },
                        new
                        {
                            ClubId = 62,
                            BrandId = 2,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/Spyder.png",
                            Name = "Spyder ZT",
                            Price = 500,
                            Stock = 12,
                            TypeId = 6
                        },
                        new
                        {
                            ClubId = 63,
                            BrandId = 3,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/Scotty-Cameron.png",
                            Name = "Scotty Cameron Santa Fe",
                            Price = 500,
                            Stock = 12,
                            TypeId = 6
                        },
                        new
                        {
                            ClubId = 64,
                            BrandId = 4,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/PLD.png",
                            Name = "PLD Anser",
                            Price = 500,
                            Stock = 12,
                            TypeId = 6
                        },
                        new
                        {
                            ClubId = 65,
                            BrandId = 5,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/MIM.png",
                            Name = "MIM Nova",
                            Price = 300,
                            Stock = 12,
                            TypeId = 6
                        },
                        new
                        {
                            ClubId = 66,
                            BrandId = 6,
                            Forgiveness = 2,
                            ImgUrl = "/images/clubs/M-Craft.png",
                            Name = "M Craft",
                            Price = 500,
                            Stock = 12,
                            TypeId = 6
                        });
                });

            modelBuilder.Entity("GolfStore.Models.Models.Clubtype", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("Clubtypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            ImgUrl = "/images/driver.png",
                            Type = "Driver"
                        },
                        new
                        {
                            TypeId = 2,
                            ImgUrl = "/images/fairwayWood.png",
                            Type = "Fairway Wood"
                        },
                        new
                        {
                            TypeId = 3,
                            ImgUrl = "/images/hybrid.png",
                            Type = "Hybrid"
                        },
                        new
                        {
                            TypeId = 4,
                            ImgUrl = "/images/iron.png",
                            Type = "Iron"
                        },
                        new
                        {
                            TypeId = 5,
                            ImgUrl = "/images/wedge.png",
                            Type = "Wedge"
                        },
                        new
                        {
                            TypeId = 6,
                            ImgUrl = "/images/putter.png",
                            Type = "Putter"
                        });
                });

            modelBuilder.Entity("GolfStore.Models.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfOrder")
                        .HasColumnType("Date");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalAmtDue")
                        .HasColumnType("real");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GolfStore.Models.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("QtyOrdered")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GolfStore.Models.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("CartTotal")
                        .HasColumnType("real");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserID");

                    b.HasIndex("ClubId");

                    b.ToTable("ShoppingCart");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GolfStore.Models.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("GolfStore.Models.Models.Club", b =>
                {
                    b.HasOne("GolfStore.Models.Models.Brand", "Brand")
                        .WithMany("Clubs")
                        .HasForeignKey("BrandId");

                    b.HasOne("GolfStore.Models.Models.Clubtype", "Clubtype")
                        .WithMany("Clubs")
                        .HasForeignKey("TypeId");

                    b.Navigation("Brand");

                    b.Navigation("Clubtype");
                });

            modelBuilder.Entity("GolfStore.Models.Models.Order", b =>
                {
                    b.HasOne("GolfStore.Models.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("GolfStore.Models.Models.OrderItem", b =>
                {
                    b.HasOne("GolfStore.Models.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfStore.Models.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GolfStore.Models.Models.ShoppingCart", b =>
                {
                    b.HasOne("GolfStore.Models.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GolfStore.Models.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GolfStore.Models.Models.Brand", b =>
                {
                    b.Navigation("Clubs");
                });

            modelBuilder.Entity("GolfStore.Models.Models.Clubtype", b =>
                {
                    b.Navigation("Clubs");
                });

            modelBuilder.Entity("GolfStore.Models.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
